[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
VITE_SUPABASE_URL="https://uhrqepfndtqrhmrckopw.supabase.co"
VITE_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVocnFlcGZuZHRxcmhtcmNrb3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczODI2MzcsImV4cCI6MjA5Mjk1ODYzN30.3_u3dbiq9oeyUm0nDtu-hXmmHtvwP-Avmplr5rwi2HE"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200